// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trrtghgwevrvtmtrrkpk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRycnRnaGd3ZXZydnRtdHJya3BrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MzYxNTEsImV4cCI6MjA3MDIxMjE1MX0.z2qSzchc6LDE7yvJjw4iz_MdWtqz-Hg0vDDw6Tt7iro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});